#!/bin/sh
set -e -x

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)

cd $ROOT_DIR_PATH

./scripts/broker-sync-submodule-config
./scripts/broker-sync-package-specs

git add packages/rabbitmq-broker/spec

./scripts/commit-with-submodule-log "$@"

git commit --amend
